version: '3.8'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./data:/var/lib/postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: netology